---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "ribocode_metaplots"
description: Set up RiboCode ORF calling with metaplots
keywords:
  - Ribo-Seq
  - Ribosome Profiling
  - ORF Calling
tools:
  - "ribocode":
      description: "A package for detecting the actively translated ORFs using ribosome-profiling data"
      homepage: "https://github.com/xryanglab/RiboCode"
      documentation: "https://github.com/xryanglab/RiboCode"
      tool_dev_url: "https://github.com/xryanglab/RiboCode"
      doi: "10.1093/nar/gky179"
      licence: "['MIT']"

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

  - annotation:
      type: directory
      description: Directory containing annotation files
      pattern: "annotation"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - config:
      type: file
      description: RiboCode configuration file
      pattern: "config.txt"

  - pdf:
      type: file
      description: PDF file containing metaplots
      pattern: "*.pdf"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@JackCurragh"
