name: "ribocode_ribocode"
description: Call ORFs with RiboCode from Ribo-Seq data
keywords:
  - Ribo-Seq
  - Ribosome Profiling
  - ORF calling
tools:
  - "ribocode":
      description: "A package for detecting the actively translated ORFs using ribosome-profiling data"
      homepage: "https://github.com/xryanglab/RiboCode"
      documentation: "https://github.com/xryanglab/RiboCode"
      tool_dev_url: "https://github.com/xryanglab/RiboCode"
      doi: "10.1093/nar/gky179"
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

  - annotation:
      type: directory
      description: Directory containing annotation files
      pattern: "annotation"

  - config:
      type: file
      description: RiboCode configuration file
      pattern: "config.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - orfs:
      type: file
      description: File containing ORFs
      pattern: "*.txt"
  - collapsed_orfs:
      type: file
      description: File containing collapsed ORFs
      pattern: "*.txt"
  - orfs_gtf:
      type: file
      description: File containing ORFs in GTF format
      pattern: "*.gtf"
  - collapsed_orfs_gtf:
      type: file
      description: File containing collapsed ORFs in GTF format
      pattern: "*.gtf"
  - orfs_bed:
      type: file
      description: File containing ORFs in BED format
      pattern: "*.bed"

authors:
  - "@JackCurragh"
